//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShelfItBase : DbContext
    {
        public ShelfItBase()
            : base("name=ShelfItBase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autor> Autor { get; set; }
        public virtual DbSet<Autor_Pozycja> Autor_Pozycja { get; set; }
        public virtual DbSet<Film> Film { get; set; }
        public virtual DbSet<Ksiazka> Ksiazka { get; set; }
        public virtual DbSet<Muzyka> Muzyka { get; set; }
        public virtual DbSet<Notatka> Notatka { get; set; }
        public virtual DbSet<Ocena> Ocena { get; set; }
        public virtual DbSet<Poz_App_Mobilna> Poz_App_Mobilna { get; set; }
        public virtual DbSet<Pozycja> Pozycja { get; set; }
        public virtual DbSet<Prosby_Wypozyczen> Prosby_Wypozyczen { get; set; }
        public virtual DbSet<Repozytorium> Repozytorium { get; set; }
        public virtual DbSet<Typ> Typ { get; set; }
        public virtual DbSet<Uzytkownik> Uzytkownik { get; set; }
        public virtual DbSet<Uzytkownik_Potwierdzenie> Uzytkownik_Potwierdzenie { get; set; }
        public virtual DbSet<Wydawca> Wydawca { get; set; }
        public virtual DbSet<Wypozyczenie> Wypozyczenie { get; set; }
    }
}
