//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repozytorium_Udostepnienie
    {
        public int udostepnienie_id { get; set; }
        public int repozytorium_id { get; set; }
        public int wlasciciel_id { get; set; }
        public int uzytkownik_id { get; set; }
    
        public virtual Repozytorium Repozytorium { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
        public virtual Uzytkownik Uzytkownik1 { get; set; }
    }
}
